version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: sdap_production_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: sdap_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: sdap_production_nginx
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./toxsign/media:/app/toxsign/media
    depends_on:
      - django
      - flower
    ports:
      - "80:80"

  redis:
    image: redis:5.0

  celeryworker:
    <<: *django
    image: sdap_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: sdap_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: sdap_production_flower
    command: /start-flower

  sdap_production_jbrowse:
    image: erasche/jbrowse
    volumes:
      - /home/genouest/bioinfo/irset/rgv/RGV/jbrowse:/opt/jbrowse
      - /groups/irset/archives/web/RGV2:/jbrowse/data
      - ./jbrowse.conf:/jbrowse/jbrowse.conf
    ports:
      - 6546:80
