# Generated by Django 2.0.13 on 2019-08-13 08:52

from django.db import migrations
from django.core.files import File
from sdap.tools.models import Category, Tag, Tool
from datetime import datetime


def populate_default_tools(apps, schema_editor):
    # TODO : Add tools here
    return



class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_auto_20190812_1432'),
    ]

    operations = [
        migrations.RunPython(populate_default_tools),
    ]
