# Generated by Django 2.2.5 on 2019-11-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20190918_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('CSV', 'Csv'), ('PDF', 'Pdf'), ('RDATA', 'RDdata'), ('EXPRESSION_MATRIX', 'Expression matrix')], default='TEXT', max_length=50),
        ),
    ]
