# Generated by Django 2.2.5 on 2019-09-30 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studies_expressiondata_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpressionStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=200)),
                ('pmid', models.CharField(max_length=20)),
                ('ome', models.CharField(blank=True, max_length=200, null=True)),
                ('technology', models.CharField(blank=True, max_length=200, null=True)),
                ('species', models.CharField(blank=True, max_length=50, null=True)),
                ('experimental_design', models.CharField(blank=True, max_length=200, null=True)),
                ('topics', models.TextField(blank=True, null=True, verbose_name='Biological topics')),
                ('tissues', models.TextField(blank=True, null=True, verbose_name='Tissue/Cells')),
                ('sex', models.CharField(blank=True, max_length=200, null=True)),
                ('dev_stage', models.CharField(blank=True, max_length=200, null=True)),
                ('age', models.CharField(blank=True, max_length=200, null=True)),
                ('antibody', models.CharField(blank=True, max_length=200, null=True)),
                ('mutant', models.CharField(blank=True, max_length=200, null=True)),
                ('cell_sorted', models.CharField(blank=True, max_length=200, null=True)),
                ('keywords', models.TextField(blank=True, null=True, verbose_name='Keywords')),
                ('data', models.ManyToManyField(related_name='studies', to='studies.ExpressionData')),
            ],
        ),
    ]
