# Generated by Django 2.2.5 on 2019-10-02 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studies', '0005_auto_20191002_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='expressionstudy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expressionstudy',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studies_expressionstudy_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
