# Generated by Django 2.2.5 on 2019-10-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0006_auto_20191002_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_id', models.CharField(max_length=50)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('symbol', models.CharField(blank=True, max_length=50)),
                ('synonyms', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('homolog_id', models.CharField(blank=True, max_length=50)),
                ('ensemble_id', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
