# Generated by Django 2.2.5 on 2019-10-19 14:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0009_database'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='apis',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
