# Generated by Django 2.2.5 on 2019-10-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0010_database_apis'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('DISABLE', 'Disable')], default='DISABLE', max_length=50),
        ),
    ]
