# Generated by Django 2.2.5 on 2019-10-20 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0011_database_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='expressionstudy',
            name='database',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_database', to='studies.Database'),
        ),
    ]
