# Generated by Django 2.2.5 on 2019-10-31 10:46

from django.db import migrations
import sys
import os
import tempfile
import shutil
from urllib.request import urlopen
from zipfile import ZipFile
import gzip
from time import gmtime, strftime
from sdap.studies.models import Gene

def insertCollections(apps, schema_editor):
    try :
        print('CreateCollection - create RGV_geneDB collection')
        #Insert Allbank ID from TOXsIgN_geneDB file
        genefile = "/app/databases_files/RGV_database_genes.txt"
        geneFile = open(genefile,'r')
        geneList = []

        for geneLine in geneFile.readlines():
            if geneLine[0] != '#':
                split = geneLine.split('\t')
                GeneID = split[0]
                print(GeneID)
                tax_id = split[1]
                homologeneID = split[2]
                ensembleID = split[3]
                Symbol = split[4]
                Synonyms = split[5]
                description = split[6]
                newGene = Gene.objects.create(gene_id=GeneID, tax_id=tax_id, homolog_id=homologeneID, ensemble_id=ensembleID, symbol=Symbol, synonyms=Synonyms, description=description)
        #Gene.objects.bulk_create(geneList)
        geneFile.close()
        print("File close")
        #shutil.rmtree(genefile[0])

    except IOError as e:
        print("args: ", e.args)
        print("errno: ", e.errno)
        print("filename: ", e.filename)
        print("strerror: ", e.strerror)



class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0012_expressionstudy_database'),
    ]

    operations = [
        migrations.RunPython(insertCollections)
    ]
