# Generated by Django 2.2.5 on 2019-11-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0016_auto_20191106_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expressiondata',
            name='cell_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
