# Generated by Django 2.2.5 on 2019-11-06 15:56

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0017_auto_20191106_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expressiondata',
            name='class_name',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), default=list, size=None),
        ),
    ]
