# Generated by Django 2.2.5 on 2019-11-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0018_auto_20191106_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='expressiondata',
            name='type',
            field=models.CharField(choices=[('2D', '2D'), ('3D', '3D')], default='2D', max_length=50),
        ),
        migrations.AddField(
            model_name='expressionstudy',
            name='status',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PRIVATE', max_length=50),
        ),
    ]
