# Generated by Django 2.2.5 on 2019-11-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0019_auto_20191125_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expressiondata',
            name='species',
            field=models.CharField(choices=[('9606', 'Homo sapiens'), ('10090', 'Mus musculus'), ('10116', 'Rattus norvegicus'), ('9913', 'Bos taurus'), ('9544', 'Macaca mulatta'), ('9823', 'Sus scrofa'), ('9031', 'Gallus gallus'), ('7955', 'Danio rerio'), ('9615', 'Canis lupus familiaris')], default='9606', max_length=50),
        ),
    ]
