# Generated by Django 2.2.5 on 2019-11-26 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0021_auto_20191126_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expressionstudy',
            name='data',
        ),
        migrations.AddField(
            model_name='expressiondata',
            name='study',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='data', to='studies.ExpressionStudy'),
            preserve_default=False,
        ),
    ]
