# Generated by Django 2.2.5 on 2019-11-28 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0024_auto_20191126_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expressionstudy',
            options={'default_permissions': ('add', 'change', 'delete'), 'permissions': (('view_expressionstudy', 'View study'),)},
        ),
    ]
