# Generated by Django 2.2.5 on 2019-11-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('studies', '0025_auto_20191128_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='expressionstudy',
            name='edit_groups',
            field=models.ManyToManyField(blank=True, related_name='edit_access_to', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='expressionstudy',
            name='read_groups',
            field=models.ManyToManyField(blank=True, related_name='read_access_to', to='auth.Group'),
        ),
    ]
