# Generated by Django 2.2.5 on 2019-11-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0026_auto_20191128_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='expressionstudy',
            name='abstract',
            field=models.TextField(blank=True, default='', verbose_name='Abstract'),
        ),
        migrations.AddField(
            model_name='expressionstudy',
            name='title',
            field= models.CharField(blank=True, max_length=200)
        ),

    ]
