# Generated by Django 2.2.5 on 2020-02-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0028_auto_20191203_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='expressionstudy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='user'),
        ),
    ]
