# Generated by Django 2.2.5 on 2020-02-18 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studies', '0029_expressionstudy_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('species', models.CharField(choices=[('9606', 'Homo sapiens'), ('10090', 'Mus musculus'), ('10116', 'Rattus norvegicus'), ('9913', 'Bos taurus'), ('9544', 'Macaca mulatta'), ('9823', 'Sus scrofa'), ('9031', 'Gallus gallus'), ('7955', 'Danio rerio'), ('9615', 'Canis lupus familiaris')], default='9606', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studies_genelist_created_by', to=settings.AUTH_USER_MODEL)),
                ('genes', models.ManyToManyField(blank=True, related_name='gene_lists', to='studies.Gene')),
            ],
        ),
    ]
