# Generated by Django 2.2.5 on 2020-04-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0030_genelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='expressiondata',
            name='jbrowse_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
