# Generated by Django 2.2.5 on 2020-04-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0031_expressiondata_jbrowse_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='expressiondata',
            name='has_jbrowse',
            field=models.BooleanField(default=False),
        ),
    ]
