# Generated by Django 2.2.5 on 2020-04-09 11:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0032_expressiondata_has_jbrowse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('species_id', models.CharField(max_length=20)),
                ('jbrowse_name', models.CharField(max_length=20)),
                ('jbrowse_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
    ]
