# Generated by Django 2.2.5 on 2020-04-09 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0033_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='expressiondata',
            name='species_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='studies.Species'),
        ),
        migrations.AddField(
            model_name='genelist',
            name='species_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gene_lists', to='studies.Species'),
        ),
    ]
