# Generated by Django 2.2.5 on 2020-04-09 12:58

from django.db import migrations
from sdap.studies.management.commands.sync_species import sync_species
from sdap.studies.models import ExpressionData, GeneList, Species

def add_species(apps, schema_editor):

    sync_species("/")

    species_dict = {}

    studies = ExpressionData.objects.all()
    gene_lists = GeneList.objects.all()
    for study in studies:
        if not study.species in species_dict:
            spec = Species.objects.get(species_id=study.species)
            species_dict[study.species] = spec
        else:
            spec = species_dict[study.species]
        study.species_link = spec
        study.save(force=True)

    for gene_list in gene_lists:
        if not study.species in species_dict:
            spec = Species.objects.get(species_id=gene_list.species)
            species_dict[study.species] = spec
        else:
            spec = species_dict[study.species]
        gene_list.species_link = spec
        gene_list.save()


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0034_auto_20200409_1256'),
    ]

    operations = [
        migrations.RunPython(add_species),
    ]
