# Generated by Django 2.2.5 on 2020-04-09 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0036_auto_20200409_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expressiondata',
            old_name='species_link',
            new_name='species',
        ),
        migrations.RenameField(
            model_name='genelist',
            old_name='species_link',
            new_name='species',
        ),
    ]
