# Generated by Django 2.2.5 on 2020-04-29 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0037_auto_20200409_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expressiondata',
            name='has_jbrowse',
        ),
        migrations.RemoveField(
            model_name='expressiondata',
            name='jbrowse_id',
        ),
        migrations.CreateModel(
            name='JbrowseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jbrowse_id', models.CharField(blank=True, max_length=200, null=True)),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jbrowse', to='studies.Species')),
                ('study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jbrowse_data', to='studies.ExpressionStudy')),
            ],
        ),
    ]
